### ISSUE TITLE
Queries against Athena (direct) are failing

### ISSUE THREAD

**Issue by madalincm** [mozilla/redash#115]
### Issue Summary:

Build identifier: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0
Window 7 64 Bit

### Steps to Reproduce:
1. Open STMO homepage - https://pipeline-sql.stage.mozaws.net/
2. Open the new query page and select Athena (direct) as data source.
3. Enter a simple query like "select * from telemetry.churn limit 20" and click the execute button

### Expected results:
The query is run, results are displayed.

### Actual results:
The query can't be executed, the following error is displayed: "Error running query: get_query_execution() only accepts keyword arguments."

### Notes/Issues:
Verified in FF54(Win7).  Issue can be reproduced in STMO-stage
Screenshot for this issue:
![athenadirecterror](https://user-images.githubusercontent.com/15685441/28125050-1f89edcc-672e-11e7-9e1e-9052be6ad92c.png)

**Comment by alison985** [comment]
This has to do with #69 - data scanned for athena

**Comment by madalincm** [comment]
I have retired this in stage today and the error message displayed is:
"Error running query: global name 'botocore' is not defined"

**Comment by alison985** [comment]
This was addressed in m6.05

**Comment by madalincm** [comment]
Queries still can't be run against Athena Direct in stage.  I always get this error: Error running query: 'Athena' object has no attribute 'run_query'
Please view this screencast:
![athenadirecterror2](https://user-images.githubusercontent.com/15685441/28212753-94e23268-68ab-11e7-8dd5-e5ef8b082990.png)

Reopening.

**Comment by madalincm** [comment]
After the recent changes queries against Athena are now running. Closing this bug and marking as verified fixed.
