### ISSUE TITLE
Unable to run JSON URL Fetcher queries

### ISSUE THREAD

**Issue by emtwo** [mozilla/redash#162]
### Steps to Reproduce

1. Go to https://sql.telemetry.mozilla.org/queries/5128#table
2. Click "Show source"
3. Click "Execute"

Expected Result: Nothing should change since the json has not changed
Actual Result: "Error running query: 'Response' object has no attribute 'update'"

**Comment by emtwo** [comment]
Hi, I'm wondering when you plan to deploy this fix?

Thank you!

**Comment by alison985** [comment]
@emtwo - should be today with the M7 release. It's already in staging.

**Comment by alison985** [comment]
@emtwo, it won't be today, sorry. M7 release is delayed.

**Comment by emtwo** [comment]
@alison985 ok no worries. thank you for keeping me posted!

**Comment by alison985** [comment]
VictorC verified fixed in QA via email on 7/31.

**Comment by emtwo** [comment]
@alison985 I still get this same error with the same STR. Does verified mean it was deployed as well? Thanks!

**Comment by alison985** [comment]
It has not been deployed yet due to another issue in the release not being QA verified yet. I'm doing the work for that now myself so this can be deployed during US daytime tomorrow (Wednesday).

**Comment by rafrombrc** [comment]
m7 has (finally!) been pushed to production, so this *should* be resolved now. @emtwo can you check and verify?
