### ISSUE TITLE
A text box widget content can’t be edited

### ISSUE THREAD

**Issue by madalincm** [mozilla/redash#54]
### Issue Summary:

Build identifier: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0
Window 7 64 Bit

### Steps to Reproduce:
1. Open a dashboard page that contains a text widget i.e. https://pipeline-sql.stage.mozaws.net/dashboard/test
2. Click on the option button and then on the edit button of the text box widget.
3. Enter some text in the text box and then click the save button.

### Expected results:
The text box widget is successfully updated.

### Actual results:
The text box widget is not updated. 

### Notes/Issues:
Verified in FF52(Win7).  Issue can be reproduced in STMO-stage and STMO-production
Screencast for this issue:
![textboxwidgetsave](https://cloud.githubusercontent.com/assets/15685441/24106636/27be9674-0d91-11e7-9522-d56939391a5a.gif)

**Comment by arikfr** [comment]
Fixed by https://github.com/getredash/redash/commit/6ff338964bd21115cbd493e7b6dc32b7aed8f0e9 (same fix as for #55).

**Comment by madalincm** [comment]
Verified as fixed in STMO-stage FF52(Win7)
The text widget content can now be edited but the changes take place even if the user does not click the save button. The changes should be saved only if the user clicks the save button.
Please view this screencast:
![postfix54](https://cloud.githubusercontent.com/assets/15685441/24503220/c6a0ace4-1559-11e7-9e96-c497387fb815.gif)

**Comment by alison985** [comment]
This is reproducible after the rebase merge on my local. While selecting "Close" will display the text changes on the close of the dialogue, if you refresh the page they aren't actually saved however. The display issue post-Close still needs addressing.

**Comment by madalincm** [comment]
I agree with Alison. After refreshing the page the changes aren't actually saved but the display issue is confusing and it should be addressed.

**Comment by alison985** [comment]
Addressed by PR #86.

**Comment by madalincm** [comment]
Verified in FF54(Win7) in stmo-stage
This issue is still reproducing. Reopening.
Please view this screencast:
![previewedittextwidg](https://user-images.githubusercontent.com/15685441/27451173-e60d2a60-5796-11e7-9a66-fca6f5a83aa3.gif)

**Comment by alison985** [comment]
@madalincm The screencast does not show you clicking the Close button, which will reset the textbox to the original text because you did not click save.

**Comment by madalincm** [comment]
@alison985 If you use the close button the issue is not reproducing but another way to close the edit Text bog window is to click somewhere else on the screen. By following this flow the issue is still reproducing.

**Comment by alison985** [comment]
Got it. Addressed in PR #95.

**Comment by madalincm** [comment]
Issue is no longer reproducing in stage. Marking as verified fixed.
